[package]
name = "grepzilla_segment"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
croaring = "2.3.1"
unicode-normalization = "0.1"

[dev-dependencies]
tempfile = "3"