name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  lint-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      # Быстрее сборка за счёт кэша Cargo
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # Если используешь Verify=PCRE2: нужны build tools
      - name: Install system deps (pcre2, pkg-config, build-essential)
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config build-essential libpcre2-dev

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: cargo fmt (check)
        run: cargo fmt --all -- --check

      - name: cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
        continue-on-error: true   # ← только этот шаг не валит джобу

      - name: cargo build (release)
        run: cargo build --workspace --release

      - name: cargo test
        run: cargo test --workspace --all-features --no-fail-fast
